server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AluEddy/springcloud-config.git
          search-paths:
            - springcloud-config
          username: AluEddy
          password: zhangdi.13903665
          default-label: master

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: configcenter
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: "*"